name: Rust

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-check:
    name: Rust Check
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Check fmt
        run: rustup component add rustfmt && cargo fmt --check

  build-nsis-plugin:
    name: NSIS plugin
    runs-on: windows-latest
    needs: [rust-check]
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: i686-pc-windows-msvc
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: installer/plugins/pingvin -> target
      - name: Build NSIS plugin
        working-directory: installer/plugins/pingvin
        run: cargo build --verbose --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nsis-plugin
          path: |
            installer/plugins/pingvin/target/i686-pc-windows-msvc/release/nsis_pingvin.dll

  build-pingvin-cli:
    name: Pingvin (${{ matrix.name }})
    runs-on: ${{ matrix.os }}

    needs: [rust-check]
    strategy:
      matrix:
        name: [linux, windows]
        include:
          - name: linux
            os: ubuntu-20.04
            # https://github.com/clap-rs/clap/issues/1938#issuecomment-632186396
            flags: ''
            artifacts: |
              target/release/pingvin-cli

          - name: windows
            os: windows-latest
            flags: -Ctarget-feature=+crt-static
            artifacts: |
              target/release/pingvin-cli.exe
              target/release/pingvin_cli.pdb

    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build CLI tool
        run: cargo build --verbose --release --bin pingvin-cli
        env:
          RUSTFLAGS: ${{ matrix.flags }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pingvin-cli-${{ matrix.name }}
          path: ${{ matrix.artifacts }}

  build-shell-extension:
    name: Shell extension
    runs-on: windows-latest
    needs: [rust-check]

    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build Shell extension
        run: cargo build --verbose --release --lib
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shell-extension
          path: |
            target/release/pingvin_share_shell.dll
            target/release/pingvin_share_shell.pdb

  create-installer:
    runs-on: windows-latest
    name: Create Installer
    needs: [build-pingvin-cli, build-shell-extension, build-nsis-plugin]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download a NSNS plugin
        uses: actions/download-artifact@v4
        with:
          name: nsis-plugin
          path: installer/plugins/
      - name: Download Shell extension
        uses: actions/download-artifact@v4
        with:
          name: shell-extension
          path: installer/files/
      - name: Download Pingvin
        uses: actions/download-artifact@v4
        with:
          name: pingvin-cli-windows
          path: installer/files/
      - name: List files
        shell: bash
        run: |
          ls -lah installer/plugins/
          ls -lah installer/files/
      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis
      - name: Print NSIS version
        run: makensis -VERSION
      - name: Create installer
        run: |
          cd installer
          makensis /DPINGVIN_CLI_EXE_PATH="$(pwd)\files\pingvin-cli.exe" /DPINGVIN_SHELL_EXTENSION_PATH="$(pwd)\files\pingvin_share_shell.dll" installer.nsi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: |
            installer/Pingvin Shell Setup.exe
